### ISSUE TITLE
Occasionally crush

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#107]
I'm experiencing this crush sometimes:

```
May 23 21:36:08 raspberrypi homebridge[1671]: crypto.js:158
May 23 21:36:08 raspberrypi homebridge[1671]: var ret = this._handle.final();
May 23 21:36:08 raspberrypi homebridge[1671]: ^
May 23 21:36:08 raspberrypi homebridge[1671]: Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
May 23 21:36:08 raspberrypi homebridge[1671]: at Decipheriv.final (crypto.js:158:26)
May 23 21:36:08 raspberrypi homebridge[1671]: at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:179:27)
May 23 21:36:08 raspberrypi homebridge[1671]: at emitTwo (events.js:106:13)
May 23 21:36:08 raspberrypi homebridge[1671]: at Socket.emit (events.js:194:7)
May 23 21:36:08 raspberrypi homebridge[1671]: at UDP.onMessage [as onmessage] (dgram.js:545:8)
May 23 21:36:08 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
May 23 21:36:08 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
```

I'm getting the same error on my S1C plugin... any idea how to solve it?

**Comment by lprhodes** [comment]
I'd start by disconnecting your S1C from the network and seeing how you go, then we can at least narrow it down a little bit.

How frequently is it happening? Are you doing anything in particular at the time?

**Comment by nitaybz** [comment]
in my S1C plugin it happened very frequently, every 15 min or so, but with you plugin, around once a day or once in 2 days.
I'm also using homebridge-broadlink-platform plugin and see the same issue happens there sometimes...

on my S1C plugin I check for the device status very frequently, every 2 seconds, so that's why it happens there much more than in the others...

**Comment by lprhodes** [comment]
but what if you take the S1C off of the network..?

All of the plugins are using a version of this https://github.com/momodalo/broadlinkjs

It may be worth asking on there and seeing what comes up - it may be as simple as checking the buffer length before trying to decrypt the data

**Comment by nitaybz** [comment]
I'm at work but will try to disconnect the S1C once I'm back home.
I'll ask there to see if they have any insights, thanks for the tip!

Not sure exactly how to execute what you suggested... but I'll check about it.

**Comment by DJay79** [comment]
Hello. I'm relatively new to homebridge so please bear with me. :)
I'm running homebridge on my Pi 2 a while now. But after installing homebridge-broadlink-rm the homebridge stop working after some time. setup the config.json with two "switch-repeat", one "switch" and one "fan" type worked so they show up in my Eve and Home App to control the devices.
All works very well until out of the blue homebridge stops.
As mentioned I'm new to this but I realized that this behavior is since homebridge-broadlink-rm.
My homebridge is configured to reboot every hour and start homebridge by "forever" 
`sudo npm install forever -g` and a script `sudo nano /etc/init.d/homebridge`

When I run in the terminal just "homebridge" to watch what is going on, it runs the whole hour.
But after auto restart, homebridge is not working anymore.

So first how can I see a log or live view what is actually happening when it stops and with what error?
And then with your help I would be great to fix it, because I wouldn't want to miss this plugin. :)

Thanks in advance for investing your time in this and for you help.

**Comment by nitaybz** [comment]
@lprhodes I did a lot of checking in the past few days... I even got to the point where I totally deleted the S1C plugin and even disconnected the device from power.
the problem still consist... just today it made my homebridge crush twice.
please help me solve it!
Thanks :)!

**Comment by lprhodes** [comment]
The issue lies with the foundation broadlinkjs module I'd suggest opening a ticket there https://github.com/momodalo/broadlinkjs
