### ISSUE TITLE
Dyson fan (AM09) - different IR codes each time power button is pressed?

### ISSUE THREAD

**Issue by wilkinsm89** [lprhodes/homebridge-broadlink-rm#184]
Any idea what is happening here? I've tried capturing the IR code but as it's different each time, it doesn't work using this plugin when I'm trying to send the code through the broadlink device.

**Comment by dermotos** [comment]
I can control mine fine (AM06). However, the power button isn't idempotent, by design. I get around this by sending a sequence to the fan. On = Speed Up, Speed Down. Off = Speed Up, Speed Down, Power Toggle.

**Comment by nickb512** [comment]
Did you have any joy with this? I have just picked up an AM09 too with the intention of controlling via SmartThings but have come across the hurdle of all the buttons sending a different code each time and this post is about the only thing that comes up on a google for this topic.

**Comment by OlliePrentice** [comment]
@nickb512 I got everything working the way I want by following the majority of this tutorial.

https://mikesgear.com/2017/09/11/control-your-homes-heating-cooling-and-more-via-ir-with-google-home-and-rm3-mini/

**Comment by nickb512** [comment]
@OlliePrentice is that with the AM09 fan?

**Comment by OlliePrentice** [comment]
@nickb512 Yeah, so I had to buy an IR blaster to send the signals to the fan. I bought the Broadlink RM Mini 3 for about £10. 

I had an old android phone lying around which I used to run the server.

**Comment by nickb512** [comment]
@OlliePrentice Yea i have that bit sussed, got the IR blaster already working controlling the TV, soundbar etc but if I put it in capture mode and point the Dyson remote at the receiver each time I press the power button the blaster detects a different code. If I capture one of those codes and then send it from the blaster it doesn't control the fan.

The only thing I can think of is its some form of rolling code encryption to make you use a Dyson remote that is new in the AM09 devices, but if you have it working with an AM09 it may not be.

Did you just capture the codes from the Dyson remote when you set it up?

**Comment by OlliePrentice** [comment]
Yeah I just captured the codes into the mini directly from the remote. Not sure why it’s not working for you.

Does it work if you try controlling it from the broadlink app?

**Comment by wilkinsm89** [comment]
@OlliePrentice Interesting that it's working for you as my AM09 generates unique power on/off codes each time.

**Comment by lprhodes** [comment]
Just tested - I too got some different codes. The first I may have long pressed it. The code wouldn't turn the Dyson on. The second time I did a short press which resulted in a shorter hex code which works to turn it on/off

"26004800471b151c151a17311530171817191719171d17171719171a161a151b141b162f17000cc4481918191719162f182e1719171a1619171b17191719171918191718171a162e18000d05"

**Comment by lomacks** [comment]
FWIW on my AM06 I get different codes each time for the same button presses - some even different lengths - however they all work and perform the desired function on the fan. There is some definite structure in the hex strings, but I haven't dug too deep into it.

For example, here are captures from pressing the "oscillate" button a few times in sequence, with a few seconds between each:

```
260048004b1a1a321b191a191b321a191a191a191a1a1b191a1a1a191b191a191a191a321a000d054a1a1a331a191b191a321a191b181b181a1b1a1a1a191b191a191a191a191a321a000d05
260024004b1a1a321b191a191b321a191a191a191a1a1b191b191a191b191a191a321a191a000d0500000000
260024004a1a1a331a191b191a321b181b181b181a1b1a1a1a191b191a191a191b181a191a000d0500000000
260048004a1a1a331a191b191a321a191b181a191a1b1a191b191a1a1a191a191a191a321a000d044b191b321b191a191b321a191a191a191a1a1b191a1a1a191a191b191a191a311b000d05
260048004b191b321a1a1a191b321a191a191a191a1a1b191a1a1a191a191b191a321a181b000d044b191b321b191a191b321a191a191a191a1a1b191a1a1a191b191a191a321a181b000d05
260024004b1a1a321b191a1a1a321a191a191a191a1b1a191b191a191b191a191a191a191a000d0500000000
260048004a1a1a331a191b191a321b181b181b181a1b1a1a1a191b191a191a191a191a321a000d054a1a1a321b191a1a1a321a191a191a191a1b1a191b191a191b191a191a191a321a000d05
260048004a1a1a331a191b191a321a191b181b181a1b1a191b191a1a1a191a191a321a191a000d054b191b321b191a191b321a191a191a181b1a1b191a1a1a191a191b181b311b181b000d05
260024004b191b321b191a191b321a191a191a191a1a1b191a1a1a191a191b191a191a181b000d0500000000
```

**Comment by lomacks** [comment]
Further to the above - I found that only some of the codes work reliably, every time. Others work intermittently or not at all. Very strange.

**Comment by ianchan0817** [comment]
@dermotos it works!

**Comment by gouldner** [comment]
I don't know the code generated because the IR blaster I am using doesn't display the read code to me but I have found the following.

If I turn the unit on with the remote and then back off again so I know the next press will turn the unit on then I record the next press as "On".
Then I record the next press after that as "Off"

Now these two codes work fine as discreet On/Off commands.  I can send "On" 10 times and it will only turn on.  It doesn't toggle.  Same works for Off.

The problem is when my AM05 loses power (I have it connected to a zwave switch for extra security that I don't leave it on all the time) and then I restore power the codes stop working or they reverse or one works and the other doesn't.

Sometimes my steps to learn on and off do not result in working discreet codes.  But when they do the unit loses them on power loss anyway.

Why would Dyson do this?  
What kind of weird IR strategy is this?

I don't understand how OlliePrentice got this working based on the article he posted.  I don't see anything in that article that addresses this issue.

**Comment by nebbles** [comment]
@gouldner The IR remote sends 4 messages per button on a cycle. The IR remote is definitely 'dumb' so it has no idea of the current product state (i.e. there is no separate on/off code).

**Comment by gouldner** [comment]
@nebbles Thanks for the info however that is not what I am finding in my testing.  I find that it actually has discreet codes however it seems to configure them on first use.  

When I test if I turn the Dyson on/off a few times and then, with the unit off, press the button and record it as ON and then press again and record as OFF.  These two recordings work as discreet ON/OFF buttons just fine.   The problem occurs when you lose power.  The next time you use the unit with the remote it seems to record the next signal as ON and the following as OFF.  This sometimes causes on recorded ON/OFF to flip how they behave or even stop working all together.  Like you said it seems to send 4 discreet messages, but the first two seem to be internally stored as discreet ON/OFF, not sure about the next two I am guessing the same.

I suspect they did this so that after a power failure the unit will ALWAYS return to OFF state.  If the remote sent two discreet on/off messages it would mean that once it goes out of sync the user would have to press the remote twice the next time they try to turn on the unit.  So instead they saved the first press as ON and the next as OFF.  I have no clue why they use 4 codes.  It seems to me 2 would have done the job.  Here I suspect they were actually trying to break the use of recording remotes so the use of a secondary remote(or in our case IR device) doesn't get the unit out of sync and cause their remote to stop behaving correctly.  Honestly I don't understand why they didn't just put two buttons On and Off on the remote and make them discreet.  It would have been SO much easier and more flexible to home automation.   For this reason I have decided to never purchase a Dyson heater or other device I might want to automate. 

The newer Dyson Hot Cool fans have automation built in with WiFi but they require the use of their app and I suspect once again they made the API closed because I can't seem to find documentation on how to interact with it.

**Comment by nebbles** [comment]
@gouldner Interesting results - which model do you have?

**Comment by gouldner** [comment]
@nebbles AM05 (mentioned in my initial comment)

**Comment by nebbles** [comment]
@gouldner I guess it depends on the IR blaster you're using. It needs to support a single button cycling through the 4 codes just as the official remote cycles through them. It seems the product is programmed to be expecting this change in the IR code to be able to identify the same button as different events. I'll try some experimentation but it sounds like the best option for you would be to DIY an IR blaster with Arduino/MicroPython/RPi which can actually cycle through commands that you record from the remote yourself.

**Comment by onefish2** [comment]
I have an AM03 and an AM04 that I want to use in HomeKit. Can anyone share the Broadlink part of their config.json with me?

**Comment by ReQuiem222** [comment]
Any Update? I can use Power on with my Am06,Am07 and Am08 but cant use power off :/
Tried already all codes in this thread

**Comment by nebbles** [comment]
@ReQuiem222 as mentioned before

> It needs to support a single button cycling through the 4 codes just as the official remote cycles through them.

It is unlikely that the Dyson machines will be able to work usual IR blasters.

**Comment by gouldner** [comment]
> @ReQuiem222 as mentioned before
> 
> > It needs to support a single button cycling through the 4 codes just as the official remote cycles through them.
> 
> It is unlikely that the Dyson machines will be able to work usual IR blasters.

I have my Dyson working with IR blaster on a Raspberry Pi.  The key is to record one command and then record the next command.  Save first as On and Second as Off.  Then stop using the hand held remote.  When the device loses power (ie is unplugged) then the first command it receives is treated and On and the Next is treated as Off so it is important to send the Saved on command first when power is lost.  If you don’t then your commands will be flipped.  Took me a while to figure out this part.   The other two of the 4 commands are never required.  The Dyson works fine with one discreet On and one discreet Off so long as you always send On first as I have described.

**Comment by nebbles** [comment]
> > @ReQuiem222 as mentioned before
> > > It needs to support a single button cycling through the 4 codes just as the official remote cycles through them.
> > 
> > 
> > It is unlikely that the Dyson machines will be able to work usual IR blasters.
> 
> I have my Dyson working with IR blaster on a Raspberry Pi. The key is to record one command and then record the next command. Save first as On and Second as Off. Then stop using the hand held remote. When the device loses power (ie is unplugged) then the first command it receives is treated and On and the Next is treated as Off so it is important to send the Saved on command first when power is lost. If you don’t then your commands will be flipped. Took me a while to figure out this part. The other two of the 4 commands are never required. The Dyson works fine with one discreet On and one discreet Off so long as you always send On first as I have described.

Nice workaround 👍  - thanks for sharing

**Comment by sunnycmf** [comment]
hello! wondering can anyone share their working version of config for AM07?
I still only get the "on" working so far :(

**Comment by griffinburkhardt** [comment]
Resurrecting this post to see if anyone can help. I am able to turn my AM09 on, but I cannot find a way to turn it off. I've tried teaching my Broadlink multiple power off codes and the speed up/speed down/power off sequence, but nothing works. I'm curious if someone can help transform the methods that work for the AM05 and AM06 into the AM09. @OlliePrentice and @lprhodes, if you still have your fan, are things working correctly? @sunnycmf, were you able to find a solution?

**Comment by rahufoxmulder** [comment]
@griffinburkhardt: have you tried this https://github.com/lprhodes/homebridge-broadlink-rm/issues/492#issuecomment-2295799553? AM06 code worked on an AM07 as self learning codes only seemed to work for "on" like your situation also.
