### ISSUE TITLE
Can't turn off switch, if they manually on from TC2

### ISSUE THREAD

**Issue by DieMetRik** [lprhodes/homebridge-broadlink-rm#190]
Hello.
I have: Broadlink RM2 Pro + Broadlink TC2(Wall light switch)+Homebridge 0.4.27 + homebridge-broadlink-rm 2.5.16
Use Broadlink TC2 for swith on/off light in bedroom.
And have next problem:

If i turn on light manually uses TC2 on wall, i can't turn off from HomeKit application (setSwitchState: already false). Need to turn on light from HomeKit and turn off(In this case works great, but it's very uncomfortable). 
I understand, there is no feedback from TC2, but homebridge can send command)

May be have some option for "switch-multi", "switch" or "light" accessory

When i use homebridge-broadlink-http there were no such problems!

**Comment by beer22** [comment]
I have the same problem with you. Not only the light but also the air conditioner. It is because the homebridge-broadlink-rm remembers the status "on" or "off". In fact, the status does not change in homebridge-broadlink-rm if you manually use the remote control. I think it is better if the system does not remember the status. If the status is "on", and I say "Hey Siri, turn on the light", the light should turn on.

**Comment by Dbarl** [comment]
I have the same problem with you.

**Comment by lprhodes** [comment]
For the switch you can use `"allowResend": true` in the config

**Comment by lprhodes** [comment]
Keep an eye on #156 for updates regarding the aircon
