### ISSUE TITLE
Learn RF code not works

### ISSUE THREAD

**Issue by MarcoVG80** [lprhodes/homebridge-broadlink-rm#226]
Hello Guys,

I attached the code and log form homebridge for learn a RF command for opening my gate. But It seems not work. I have try with Broadlink RM pro and RM pro plus .

Thanks a lot,

Marco

**Comment by S474N** [comment]
Same problem, have Broadlink RM PRO and in console this problem:
`[2018-1-19 18:27:28] [Broadlink RM] Scan RF (RF learning not supported for device at 192.x.x.x)`

In eControl app is everything OK.

**Comment by lprhodes** [comment]
@MarcoVG80 Are you seeing the same issue as @S474N  on your Broadlink RM pro (not plus)?

@S474N Is yours a PRO Plus?

**Comment by S474N** [comment]
No, "only" RM PRO (about 4-5 years old).

**Comment by lprhodes** [comment]
@S474N Did the original RM PRO definitely have RF support?

**Comment by S474N** [comment]
Look, I wrote, that via eControl app is everything OK. Of course I can control RF sockets.

**Comment by lprhodes** [comment]
I must have missed that after having gone through 100 issues today. It would be worth sounding a little less hostile in response to people trying to help.

As I don't have a 4-5 year old RM Pro there's nothing else I can do here. That message appears because it's not defined as having RF support by https://github.com/momodalo/broadlinkjs so I suggest you start there.

**Comment by S474N** [comment]
OK, thanks for reply. Is some way, to explore exactly version of RM PRO via CLI?
