### ISSUE TITLE
Network Overtime

### ISSUE THREAD

**Issue by doodoovane** [lprhodes/homebridge-broadlink-rm#227]
Hello everybody,

I've got some issues with my broadlink rm pro recently bought. After several minutes working, I can't reach it using homebridge. 
When I  try with the e-control app, it shows me NETWORK OVERTIME.

Is there someone having the same issue and also how did you managed to solve it?

Thank you for reading

**Comment by lprhodes** [comment]
Perhaps it needs a software update?

**Comment by dutch-anykey** [comment]
same here,

2018 Original Broadlink RMPro+ and RMmini3.
It just stops working for a few minutes, then accepts commands for a few minutes again, and this keeps repeating. So connection is not stable. I just about checked everything in my network. But can't seem to find it.
Some test i do to see if connection is op is going to the device tab and request firmware status. So every few minutes it reports back that the fw is the latest version, and when it refuses i get "network overtime"

- Tried both apps, IHC and E-control (both from ios device)
- initial setup is no problem
- latest firmware
- assigned static adress in router
- tried two different routers 
- in dos box opened a continious ping and even when it refuses to send a command, the ping keeps working.
- sometimes when connection is restored again, it sends a batch of commands. So I think there is some buffer that eventually can send the commands that where given before and failed.

These devices still seem to be the ticket for what i want to use it for (Alexa home automation), but this problem is driving me nuts.  It's already going wrong in the broadlink app. Even before I tried to include alexa in the mix.

How is the connection diagram? Does the app communicate with the rm's directly or is the app communicating via internet and internet towards the rm's again?
 
Perhaps I could try and fall back to the android bridge solution?

kind regards,
Maurice

**Comment by cubilon** [comment]
@dutch-anykey, got more than one Broadlink on you network? I mean, one Broadlink RMPro+ and one RMmini3? Have they a fixed IP?

**Comment by dutch-anykey** [comment]
Hi cubilon,

Yes I have both RMmini3 and RMPro+ in the network with a fixed IP (reserved dhcp adress) But anyway, one was shut down during testing, and still the same result.

kind regards,
Maurice

**Comment by dutch-anykey** [comment]
Hi,

It is still driving me mad. Still the same issue, i really wonder if more people have this problem. I once had it stable after re0initializing the RMPRO+ via AP mode. It kept stable until you reboot the RMPRO+ (i had to physically move it so it was powerless for a moment) After that same problem again (Also the rmmini) It has to do with the network i.m.o. Or at least the broadlink device not cooping with something. I have to mention that all other devices in the network are happy with my ases router....I have reconfigured the complete home network to see if it helps. Only to get these POS broadlink devices get to work :(
Sorry, just very frustrated at this moment. Just about ready to go buy a harmony hub and be done with it. Only thing missing then is the airco control.
