### ISSUE TITLE
Latest node version installed but still reading old node version, still persists

### ISSUE THREAD

**Issue by peterlbk** [lprhodes/homebridge-broadlink-rm#261]
Following up on issue 204, i get the same error, triggered by 

Error: Homebridge plugins that use the "homebridge-easy-platform" library require your node version to be at least v7.6.0. Current version: v6.12.2
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:4:48)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/index.js:1:90)
    at Module._compile (module.js:570:32)

Please check, my node -v is
node -v
v8.9.1

nvm list
->       v8.9.1
         system
default -> 8.9.1 (-> v8.9.1)
node -> stable (-> N/A) (default)
unstable -> 8.9 (-> v8.9.1) (default)
iojs -> iojs- (-> N/A) (default)

**Comment by LucLisette** [comment]
Sorry i don't know where to be, so I guess.


Hey, I am new with almost no experiance and my english is bad. Do not know if I am in the right topic?My RBPi 3 is running stretch. I can not get homebridge to run.this is what I get. Can someone help please.pi@raspberrypi:~ $ sudo systemctl status homebridge.service -l● homebridge.service - HomeBridge ServiceLoaded: loaded (/lib/systemd/system/homebridge.service; enabled; vendor preset: enabled)Active: failed (Result: exit-code) since Sat 2018-02-17 12:14:01 CET; 8min agoMain PID: 25566 (code=exited, status=1/FAILURE)feb 17 12:13:59 raspberrypi node[25566]: *** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodefeb 17 12:13:59 raspberrypi node[25566]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only suppfeb 17 12:13:59 raspberrypi node[25566]: *** WARNING *** Please fix your application to use the native API of Avahi!feb 17 12:13:59 raspberrypi node[25566]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSSerfeb 17 12:14:01 raspberrypi homebridge[25566]: [2018-2-17 12:14:01] Loaded plugin: homebridge-gpio-relayfeb 17 12:14:01 raspberrypi homebridge[25566]: [2018-2-17 12:14:01] Registering accessory 'homebridge-gpio-relay.relay'feb 17 12:14:01 raspberrypi homebridge[25566]: [2018-2-17 12:14:01] ---feb 17 12:14:01 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILUREfeb 17 12:14:01 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.feb 17 12:14:01 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.lines 1-15/15 (END)
--

**Comment by theo-69** [comment]
@LucLisette totally wrong this is for a broadlink homebridge pluin try [https://github.com/nfarina/homebridge](https://github.com/nfarina/homebridge)

**Comment by lprhodes** [comment]
@peterlbk You'll need to use other resources such as Stack Overflow sorry
