### ISSUE TITLE
homebridgeDirectory enhancement request

### ISSUE THREAD

**Issue by cubilon** [lprhodes/homebridge-broadlink-rm#311]
on my raspi I have two different users, "homebridge" - used for homebridge daemon service runtime - and "pi" for all other purposes. 
the daemon starts homebridge from /var/homebridge; when I stop it and I make my experiments or test some different configuration I do it from /home/pi/.homebridge. when I finish testing a configuration, I copy config.json from the second path to the first, and I relaunch the daemon.

the problem is that while I move on /var/homebridge, I need to indicate that path on "homebridgeDirectory" parameter on config.json, otherwise the daemon doesn't start. this happend only with your (fantastic) plugin, becouse the others don't matter where your're launching homebridge from.

a good enhancement could be removing the need to indicate "homebridgeDirectory" and let plugin work from every path without the need to indicate that.

thanks for the attention and thanks for your work!

**Comment by lprhodes** [comment]
It's only used to determine where the accessory state database is stored.

It's usually automatic because it uses one of the following environment variables as the root path

- HOME
- HOMEPATH
- USERPROFILE

Then `.homebridge/plugin-persist/homebridge-broadlink-rm` is appended to the path.

When none of those environment variables are found and `homebridgeDirectory` hasn't been set, the module will currently ends up trying to write to `/plugin-persist/homebridge-broadlink-rm` which it generally cannot do.

For just you use case you could set one of the above environment variables for the daemon user but for a more general solution, ideally we'd find another environment variable that we could check for.

**Comment by cubilon** [comment]
Ok, I'll try this solution. I'll let you know!
