### ISSUE TITLE
Error reported on max temperature

### ISSUE THREAD

**Issue by iandronowicz** [lprhodes/homebridge-broadlink-rm#319]
I saw this on my log:

[3/20/2018, 7:12:57 AM] [Broadlink RM] Aire Acondicionado Living onTemperature (24.6)
[3/20/2018, 7:12:57 AM] [Broadlink RM] Aire Acondicionado Cuarto De Invitados onTemperature (23.9)
[3/20/2018, 7:12:57 AM] [Broadlink RM] Aire Acondicionado Cuarto Principal onTemperature (249)

/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/chai/lib/chai/assertion.js:141
      throw new AssertionError(msg, {
      ^
AssertionError: [CONFIG ERROR] maxTemperature (40) must be more than the reported temperature (249): expected 249 to be below 41
    at AirConAccessory.onTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:366:12)
    at emitOne (events.js:116:13)
    at device.emit (events.js:211:7)
    at device.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:427:22)
    at emitTwo (events.js:126:13)
    at device.emit (events.js:214:7)
    at Socket.cs.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:245:18)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:658:8)

[3/20/2018, 7:13:08 AM] Loaded plugin: homebridge-broadlink-rm
[3/20/2018, 7:13:08 AM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[3/20/2018, 7:13:08 AM] ---

From what I understand there is a mix up in unit fo the temperature? because I set max temp at 40C and I think that it is comparing it to 249F?

Im not sure...

**Comment by cubilon** [comment]
+1

**Comment by nickkkk72** [comment]
+1 same issue. One time per day... :-((
This issue crash directly homebridge and impossible to restart homebridge service or app. 
Must delete accessories and persist to get homebridge works again...

**Comment by nickkkk72** [comment]
Update... removing accesories and persist is not enough... had to remove homebridge bridge from HomeKit and add it again (with his 60 accessories to add, rename, place to rooms, etc...). So one time per day... a little bit boring... please help us. 
Previous @iandrnowicz comment (about mix between C and F temp) makes sense no ?
Fyi : my MaxTemp in config.json was 40, and set 250 deg for testing... same issue..

**Comment by iandronowicz** [comment]
@nickkkk72 homebridge is working just fine, you don’t have to do anything... I have it as a service with the KeepAlive flag on true so when it crashes it just restarts and everything works fine... at least for a while until it’s fixed

**Comment by nickkkk72** [comment]
@iandronowicz Ahhhh ????
After getting the error message, homebridge crash and you’re right, restart if it run as a service, but since the error time, all my devices stop responding... 
nothing to do for me... restart my Rpi, remove or rename persist and accessories, restart home app, reboot my iPhone, etc...

I think the first time, the’ve still respond, but after a very long time (maybe the time need to my iPad hub to find all accessories again ?)

**Comment by iandronowicz** [comment]
Honestly I don’t even notice when it crash. I would have to acces the home app just at the same time as homebridge crashes, and that hasn’t happen yet.

**Comment by nickkkk72** [comment]
@iandronowicz Ok... perhaps due to my specific configuration so... have you got other homebridge plugins ?

**Comment by iandronowicz** [comment]
@nickkkk72 just BroadlinkRM running on my MacMini server. A while ago I had to move other plugins (BroadlinkS1C, BradlinkPlatform and mqtt-switch-tasmota) to a Raspberry Pi 3 because one of them was crashing everything. Eventually the developer fixed it but I kept the same 2 separate home bridge server config.

**Comment by nickkkk72** [comment]
Ok. By my side, my plugins are Broadlink, eDomoticz, and Melcloud (Mitsubishi AC). I got exactly 72 Devices managed by homebridge bridge. I run iOS 11.2.6 on IPhone X. Got an Apple TV to share HomeKit to outside. 
Got a second Rpi for a second homebridge service (garage opener) and this one works like a charm since 2 years...
Si, it will probably not solve all my issues (first Rpi), but if @lprhodes can fix the maxtemp issue... it will help us a lot. 

(And thank you lprhodes for this excellent plugin....)

**Comment by lprhodes** [comment]
Hey,

I'm struggling to see the exact issue here.

@iandronowicz Regarding the 249, I'm not doing any temperature conversions so I guess the broadlink is just sporadically sending ridiculous temperatures. It looks like it could be 24.9 though judging by the other temperatures so perhaps the Broadlink RM is messing up it's calculations at some point.

That's just a guess though so in 3.3.2 I've made it so that if anything about `maxTemperature` is reported then it gets altered to be `maxTemperature`. It will output an `[Info]` log when that happens to keep an eye on it and if it is in fact a bad calculation then I could imply divide it by 10 if it's too high. Let me know.

@nickkkk72 It sounds like you're having a slightly different issue. Could you create a new issue please and include logs from the time that it crashes please. Make sure you're on the latest version.

**Comment by nickkkk72** [comment]
Hi @lprhodes . Nice that i can thank you directly for your plugin again, and for support.... 

I had 2 differents issues. The first one was this initial post (actual temp is « 249 » degrees and crash. 

The second one needs effectively a new issue there, but i want to investigate more first. If it will be ok, i will report it why and if not i will open new issue. 

Thanks again... gonna try last release immediatly !!!
