### ISSUE TITLE
hello~I got an Air con issues about cool and heat mode

### ISSUE THREAD

**Issue by Warden630** [lprhodes/homebridge-broadlink-rm#34]
while now I can set any temperature listed blow through SIRI , but not with any cooling or heating state.  and I touch the "cool" and "heat" buttons in the AC icon within Home app but nothing happens.
here is my config.json:

{
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "accessories":[
{
  "name":"客厅空调",
"type":"air-conditioner",
 "data":{
            "off":"2600c800c8f21236.....",
	    "on":"2600c800c8f21236.....",
            "temperature28":{
              "pseudo-mode":"heat",
           "data":"2600c800c8f21236....."
            },
            "temperature27":{
              "pseudo-mode":"heat",
              "data":"2600c800c8f21236....."
            },
            "temperature26":{
              "pseudo-mode":"heat",
              "data":"2600c800c8f21236....."
            },
            "temperature25":{
              "pseudo-mode":"cool",
              "data":"2600c800c8f21236....."
            },
            "temperature24":{
              "pseudo-mode":"cool",
              "data":"2600c800c8f21236....."
            },
            "temperature23":{
              "pseudo-mode":"cool",
              "data":"2600c800c8f21236....."
            }
          }
        }
      ]
}

I thought maybe because it didn't define "cool" and "heat" hex code, so that I put
`"cool":"2600c800c8f21236.....",
"heat":"2600c800c8f21236....."`
in the config.json but the whole homebridge service just went wrong.
so, is it something i put wrong? how should I define cool and heat mode hex code?
thank u very much!

**Comment by lprhodes** [comment]
Air conditioners send all of their information in one IR blast/hex code which means we can't just change the mode from heat to cool without getting a hex code for ever heat/temperature cool/temperature combination.

For that reason the plugin fakes whether the mode is cooling or heating from 'pseudo-mode' so that the colour changes in the Home app.

When you press Cool it will try set the temperature to whatever "defaultCoolTemperature" is (defaults to 16). When you press Heat it will try set the temperature to whatever "defaultHeatTemperature" is (defaults to 30)

Also make sure you set "minTemperature" and "maxTemperature" values to whatever you want them to be if you're not providing the defaults (16 and 30)

Finally, update to the latest release (version 1.1.2).
