### ISSUE TITLE
Send codes independently of the state

### ISSUE THREAD

**Issue by jesusmarcos** [lprhodes/homebridge-broadlink-rm#396]
I have different RF outlets to control lights at home. Those outlets can be controled with the help of your plugin from HomeKit or directly with their remote control.

If the outlet is ON and I switch it off from the remote control, Homekit shows it as On (what is normal as there is no two-way communication).

If now I ask Siri "Switch on the lamp", I receive a message in the console from the plugin saying that the accessory is already on and does not send the code to switch it on, so I have to switch it on again from the remote control.

Is there any way that we can bypass the status control when giving the order directly with Siri for certain accessories?  This will allow me to send the on or off codes independently from the state using Siri.

Many thanks

**Comment by Kung-Foo-Kamel** [comment]
I have this very same issue, and to make it worse, if homebridge drops its connection, as it seems to do often, and you send the "off" command, Siri will toggle the switch, but obviously the light has not responded, once homebridge gets its connection back, asking Siri to turn the light off again, will respond in no action taken as she thinks the light is already off, but clearly to me, its still on, I must ask her to turn the light on, then off in order to recover.

I'm not sure what devices other people are using, but none of my RF devices can send status back to Homebridge.

If I could fit a sensor to the active and neutral wires of the actual light and send a signal back to Homebridge to update the "real" status then this would be fantastic, but I don't see this as an easy task.

If I use Alexa, this problem doesn't happen, as she does not give a rats backside what state the light/switch is in, she will send the command you have asked her to send.

Is there a signal that we can we can send to Homekit say status "Unkown"

Below is the error I get when I switch the light on from the wall or its remote and I ask Siri to turn it off:

[2018-7-3 05:18:13] [Broadlink RM] Cinema Room setSwitchState: false
[2018-7-3 05:18:13] [Broadlink RM] Cinema Room setSwitchState: already false (no data sent - B)

**Comment by doner005** [comment]
I am also looking for a solution to this. I have the same problem if I use the RF remote for my ceiling fan/light combo.

**Comment by doner005** [comment]
Try adding ‘“allowResend”: true’ to your commands.

This works for me. Give it a shot.

**Comment by Kung-Foo-Kamel** [comment]
Awesome, will give this a shot, were did you find the reference for this?

**Comment by jesusmarcos** [comment]
It works perfectly. Thanks a lot. :-)

I couldn't find information about any property with that purpose.

Many thanks again.

**Comment by doner005** [comment]
I could only find reference to this command in an old issue that was created. I didn’t see anything about it in the plugin documentation. 

https://github.com/lprhodes/homebridge-broadlink-rm/issues/176

**Comment by carolinomv** [comment]
Hello guys! Any news on “allowResend”: true, for window covering?

**Comment by Kung-Foo-Kamel** [comment]
Works for my lights and switches, but I have no idea if it works for blinds.

I think this is abandon-ware as there has been no updates on anything that I'm aware of, I'm slowly moving everything over to native Homekit control as reliance on these plugins can be a little challenging, specially if Homebridge gets a major update and things start to break.

Happen to my Yeelights twice, Domiticz adn my Harmony hubs have never worked after that plugin broke.

**Comment by huongminh** [comment]
“allowResend”: true works for fans as well. Great!
For window coverings, i'm afraid not since the logic to control blinds this plug in uses is time based to remember the current blind position. So previous value should be referred to every time a command is made.

**Comment by hepcat72** [comment]
OK. Great.  `allowResend` - it would be nice to know where to put this without guessing.  Does it go in each accessory or can I put it at the level with the platform to globally set it, because it seems like this should be a default since no IR devices I've seen talk back.

**Comment by hepcat72** [comment]
For anyone else finding themselves here - it goes inside each accessory.
