### ISSUE TITLE
How can I replace the "switch-repeat" accessory?

### ISSUE THREAD

**Issue by NoTrace-Kai** [lprhodes/homebridge-broadlink-rm#434]
Hi there ...

i upateted my Homebridge / Node and NPM to the lastes Verseion ...
But now the Homebridge logfile shows that on start:

The "switch-repeat" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm

I set my switches to repeat sending the HEX code 4 times, because some 433 mhz power plugs are far away and that was the easiest way to get them all workin ;)

What can i use instead? Or can I use the "switch-repeat" like it is?

Greetings Kai

**Comment by DJay-X** [comment]
I also noticed this message "switch-repeat" accessory is now deprecated and shall be removed in the future." a couple of month ago. But I hope the developer will keep it working, like it is.
I have some of switch-repeat and have not clue how to get them to work in a new way. 
So fingers crossed we can use it ongoing with  switch-repeat. 
For now, @NoTrace-Kai just ignore the message like I do since months. Everything is working fine.

**Comment by lprhodes** [comment]
If/when I remove it I'll be sure to add some migration docs.
