### ISSUE TITLE
TypeError:dev.device is not a function

### ISSUE THREAD

**Issue by cuihaijun** [lprhodes/homebridge-broadlink-rm#47]
``/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98
 ``       dev.device();
``            ^
``
``TypeError:dev.device is not a function
 ``   at module.exports.Broadlink.genDevice (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98:13)
``    at Socket.cs.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:187:29)
``    at emitTwo (events.js:106:13)
``    at Socket.emit (events.js:194:7)
 ``   at UDP.onMessage [as onmessage] (dgram.js:545:8)

**Comment by lprhodes** [comment]
It sounds like there's an unsupported broadlink device on the network. To figure out which one  try turning them off one by one and starting homebridge again. Let me know which model is the culript and I'll see if there's anything I can do to support it or at the very least, ignore it.

**Comment by lprhodes** [comment]
Alternatively you can run `npm i broadlinkjs@"git+https://github.com/lprhodes/broadlinkjs.git" -g` and that will just ignore the error-causing device

**Comment by Warden630** [comment]
I got the same problem.
It still go like this after run `npm i broadlinkjs@"git+https://github.com/lprhodes/broadlinkjs.git" -g`
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98 dev.device();
^
TypeError:dev.device is not a function at module.exports.Broadlink.genDevice (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98:13)
at Socket.cs.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:187:29) at emitTwo (events.js:106:13)
at Socket.emit (events.js:194:7) at UDP.onMessage [as onmessage] (dgram.js:545:8)

maybe because I got an Glanz airconditioner oemed by broadlink?
