### ISSUE TITLE
Shades percentages

### ISSUE THREAD

**Issue by Cloudore** [lprhodes/homebridge-broadlink-rm#52]
Hey, first of all, great work on the plug-in, thanks for making it!

I have a couple of questions regarding the window covering service that I'd appreciate if anyone could clear before going ahead and buying the rm pro:

Is the "off value" for windows coverings supposed to be the "Stop" button on my controller? Do percentages like opening a covering to 50% work? What about if I set a scene with 5 shades and set them all to close, will the codes overlap and cause none of them actually executing?

These are the problems I have with my current set up, GPIO transmitter and receiver connected to the homebridge-blinds plug in, so I wanted to know if buying an rm pro and using this plug in might solve that issue.

Also, is there a way to easily sniff the rf codes needed in the json with the broadlink?

Thanks in advance!

**Comment by lprhodes** [comment]
I've just published 1.4.0 which changes "off" to "stop" so that it's clearer.

Percentages do work.

Setting them to open doesn't work right at this moment but will in the next 30 minute and then I'll be able to tell you if the scene works in terms of HomeKit.

If you have any issues with overlap with scenes then I could add a "startDelay" config setting which would force each shade to open slightly later than the next. Unsure if you'll see this issue though.

The state of learning RF can be tracked here https://github.com/lprhodes/homebridge-broadlink-rm/issues/29

**Comment by lprhodes** [comment]
Scenes work with 1.4.0 but only through Siri - there looks to be a bug within Apple's Home app. Scenes also work fine in other apps like the unofficial Home app.
