### ISSUE TITLE
Fan Control is recognise as Aircon in Home App

### ISSUE THREAD

**Issue by zfoo83** [lprhodes/homebridge-broadlink-rm#623]
Hi, 
I need some help here. I am having issue where type "fan", it is recognize as A/C control in the home app on iPhone. Is there anything wrong i did?

            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "accessories": [
                {
                    "name": "Fan On/Off",
                    "type": "fan",
                    "data": {
                        "on": "2600a2006e761d581c571d1c1d571d571d571d1c1d1c1c1c1d1c1d1c1d571d1b1d1c1d571d1c1d1c1c1c1d581c571d571d571d571d1c1d00047d72771c581d571d1c1b581c581c591b1d1c1d1c1d1c1d1c1c1c581c1d1c1d1b591b1d1c1d1c1d1c581c581c581c581c5a1a1d1c00047d72771c581c581c1d1c581c581c581c1d1c1d1b1d1c1d1c1d1b591b1d1c1d1c581c1d1c1d1b1d1c581c581c581c581c581c1d1c000d05000000000000",
                        "off": "2600a2006e761d581c571d1c1d571d571d571d1c1d1c1c1c1d1c1d1c1d571d1b1d1c1d571d1c1d1c1c1c1d581c571d571d571d571d1c1d00047d72771c581d571d1c1b581c581c591b1d1c1d1c1d1c1d1c1c1c581c1d1c1d1b591b1d1c1d1c1d1c581c581c581c581c5a1a1d1c00047d72771c581c581c1d1c581c581c581c1d1c1d1b1d1c1d1c1d1b591b1d1c1d1c581c1d1c1d1b1d1c581c581c581c581c581c1d1c000d05000000000000",
"swingToggle": "2600a2006e761d581c571d1c1d571d571d571d1c1d1c1c1c1d1c1d1c1d571d1b1d1c1d571d1c1d1c1c1c1d581c571d571d571d571d1c1d00047d72771c581d571d1c1b581c581c591b1d1c1d1c1d1c1d1c1c1c581c1d1c1d1b591b1d1c1d1c1d1c581c581c581c581c5a1a1d1c00047d72771c581c581c1d1c581c581c581c1d1c1d1b1d1c1d1c1d1b591b1d1c1d1c581c1d1c1d1b1d1c581c581c581c581c581c1d1c000d05000000000000",

**Comment by ffaamm** [comment]
I second this, type `fan` is currently recognized by the Home app as an air conditioner.
Homebridge Config UI X itself identifies the accessory as a thermostat.

```
Node.js v12.16.3
npm v6.14.5
Homebridge v1.0.4
Homebridge Config UI X v4.18.0
Homebridge Broadlink Rm v3.6.22
```

**Comment by ffaamm** [comment]
Found it, it's a bug introduced in `accessories/fan.js` and `accessories/garageDoorOpener.js` after 3.6.18:
[`accessories/fan.js`](https://github.com/lprhodes/homebridge-broadlink-rm/commit/ccb3fff578ee24c3673b908eded4073773be6026#diff-e5e9ad8be47ce9d631ec056fc292b99b)
[`accessories/garageDoorOpener.js`](https://github.com/lprhodes/homebridge-broadlink-rm/commit/ccb3fff578ee24c3673b908eded4073773be6026#diff-b85751f6b8babb4f681ea5754e7615b7)

Downgrading to 3.6.18 can be a temporary workaround until it's fixed.

This issue is also a duplicate of #616, #602, and #594.

**Comment by zfoo83** [comment]
It works like charm! Thank you for your help!!
