### ISSUE TITLE
Broadlink TC2

### ISSUE THREAD

**Issue by hillaliy** [lprhodes/homebridge-broadlink-rm#69]
Hi I can't get the hex code from the tc2 switch.
Do you have any solution?

**Comment by lprhodes** [comment]
What happens with you try learn it with the offical Broadlink app?

**Comment by hillaliy** [comment]
it's works perfect with the official Broadlink app.

**Comment by lprhodes** [comment]
Do you press Learn or Sweep Frequency in the broadlink app?

**Comment by hillaliy** [comment]
Maybe I do something wrong. can you tel me how to configure the TC2 with homebridge?

**Comment by hillaliy** [comment]
I have Scan RF and Learn IR on the homekit app.
I success to learn air conditioner ir and it's work.

**Comment by lprhodes** [comment]
In the broadlink app though- which button do you press. learn or sweap ?

**Comment by hillaliy** [comment]
I press add remote, the tc2 and on the tc2 switch i press for 5 sec and it start to blink and then the app get it

**Comment by hillaliy** [comment]
i have tc2 2 gang

**Comment by lprhodes** [comment]
Ok I can only guess but you should be able to use the Scan RF accessory and follow the instructions shown in the homebridge logs

**Comment by mrblack7** [comment]
The TC2 is a Broadlink product, so it doesn't need to 'learn' it as such.

**Comment by hillaliy** [comment]
so how do i configure it to work with homebridge?

**Comment by lprhodes** [comment]
It looks like people have had success by doing the following:

1. Pair with broad link app
2. Use a universal garage remote to learn the code (one that support 433mhz I believe)
3. Use the normal learning mode to learn the code from the remote (hold the remote extremely close to the RM device)

Information from https://github.com/mjg59/python-broadlink/issues/21#issuecomment-264884804

**Comment by Referor** [comment]
Another way, but you still need 2 devices and RM Pro plus (this way work for TC2) for me:
1. First IOS device(to control e-control app). In your e-control application you need to have already educated TC2 remote / TC1 remote. 
2. Second IOS device with homekit and homebridge with scan_frequency function (to control your homebridge) / Mac (OS Mojave beta have home kit application)
Algorithm:
1) You need to start "Scan_frequency" in your homebridge with second device
2) You need to push the preferred button at your first device several times
And you can add buttons step-by-step to your homebridge. 
I think we can use this algorithm because RM Pro can scan frequency and send frequency in same time. We start scanning process and then we send some RF frequency in this one RM Pro plus device
